export const projects = [
  {
    title: 'Restaurant Menu',
    description: "The Modern Restaurant Application is a fully responsive solution designed to enhance the dining experience. Inspired by the latest menu apps, this project was expertly crafted using Figma for design and a combination of JavaScript, React, and CSS for development. The end result is a sleek and professional application that seamlessly adapts to any device for optimal user engagement.",
      imageP: '/images/Restaurante/1.png',
    images:['/images/Restaurante/1.png','/images/Restaurante/2.png','/images/Restaurante/3.png','/images/Restaurante/4.png','/images/Restaurante/5.png','/images/Restaurante/6.png','/images/Restaurante/7.png','/images/Restaurante/8.png','/images/Restaurante/9.png','/images/Restaurante/10.png'],
    tags: ['React', 'JavaScript'],
      tags: ['React','JavaScript', 'Figma'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'GPT-3',
    description: "The app interface was inspired by GPT-3 technology and designed using Figma. The development process utilized JavaScript, React, and CSS to bring the design to life.",
    images:['/images/gtp-3/gtp3b.png',],
    imageP: '/images/gtp-3/gpt3.png',
    tags: ['React','JavaScript', 'Figma'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Tanno',
    description: "As a UX/UI Designer, I was a key member of a team that designed and researched the user experience and overall design of an electric motorcycle project. Our efforts resulted in securing a sponsorship to bring the concept to life. To further showcase the business value of the motorcycle, I utilized Keyshot to create a high-quality rendered video that accurately represents the final product.",
    imageP: '/images/tanno/1.jpeg',
    images:['/images/tanno/1.jpeg','/images/tanno/3.jpeg','/images/tanno/TANNO.png','/images/tanno/2.jpeg',],
    tags: ['React','JavaScript', 'Figma'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Serena',
    description:"The project focuses on enhancing the user experience and ergonomics of a solar-powered boat by conducting thorough research and applying design improvements. The goal is to increase the boat's value to the business through optimized design and structure, as demonstrated through professional renderings.",
    imageP: '/images/Serena/bote1.png',
    images:['/images/Serena/bote1.png','/images/Serena/Serena.png',"/images/Serena/bote.jpeg","/images/Serena/bote1.png"],
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Grow and learn with me',
    description: "The main objective of this project was to enhance the learning experience of children with Down's Syndrome. Through thorough research and analysis, a UX-UI design solution was developed in the form of a specialized child's desk. The desk is equipped with various features and elements aimed at aiding the children in their academic pursuits and promoting their cognitive development.",
    imageP: '/images/mesa/mesa2.PNG',
    images:['/images/mesa/mesa2.PNG','/images/mesa/mesa1.png','/images/mesa/mesa.PNG','/images/mesa/mesa3.png',],
      tags: ['UX-UI','Adobe-Photoshop','Keyshot', 'Solidworks'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Viewpoints ',
    description: "After conducting an extensive research of building structures and viewpoints, I utilized the 3D modeling software Solidworks and the visualization tool KeyShot to construct two distinct viewpoints. This approach effectively demonstrated the intended outcome of the project as if it were a real implementation.",
    imageP: '/images/MiradorAgua/m1.jpg',
    images:['/images/MiradorAgua/m1.jpg',"/images/MiradorAgua/Mirador.png",'/images/MiradorAgua/m3.png','/images/MiradorAgua/m4.png',],
    tags: ['UX-UI','Adobe-Photoshop','Keyshot', 'Solidworks'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Renders',
    description: "Utilizing advanced design tools such as Creo Parametric and KeyShot, i specialized in creating professional-grade models and renders of various elements, all adhering to a consistent design architecture",
    imageP: '/images/Renders/3.png',
    images:['/images/Renders/3.png','/images/Renders/4.png','/images/Renders/5.png','/images/Renders/6.png','/images/Renders/7.png','/images/Renders/8.png','/images/Renders/9.png'],
    tags: ['React','JavaScript', 'Figma'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];

export const MeDraw={image:'/images/YoDibujada.png'};